// @generated by protoc-gen-es v1.10.0
// @generated from file chat.proto (package viamlabs.service.chat.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Struct } from "@bufbuild/protobuf";

/**
 * @generated from message viamlabs.service.chat.v1.ChatRequest
 */
export const ChatRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viamlabs.service.chat.v1.ChatRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 99, name: "extra", kind: "message", T: Struct },
  ],
);

/**
 * @generated from message viamlabs.service.chat.v1.ChatResponse
 */
export const ChatResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viamlabs.service.chat.v1.ChatResponse",
  () => [
    { no: 1, name: "answer", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

