/**
 * @fileoverview gRPC-Web generated client stub for viamlabs.service.chat.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: chat.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_api_annotations_pb = require('./google/api/annotations_pb.js')
const proto = {};
proto.viamlabs = {};
proto.viamlabs.service = {};
proto.viamlabs.service.chat = {};
proto.viamlabs.service.chat.v1 = require('./chat_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.viamlabs.service.chat.v1.ChatServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.viamlabs.service.chat.v1.ChatServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.viamlabs.service.chat.v1.ChatRequest,
 *   !proto.viamlabs.service.chat.v1.ChatResponse>}
 */
const methodDescriptor_ChatService_Chat = new grpc.web.MethodDescriptor(
  '/viamlabs.service.chat.v1.ChatService/Chat',
  grpc.web.MethodType.UNARY,
  proto.viamlabs.service.chat.v1.ChatRequest,
  proto.viamlabs.service.chat.v1.ChatResponse,
  /**
   * @param {!proto.viamlabs.service.chat.v1.ChatRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.viamlabs.service.chat.v1.ChatResponse.deserializeBinary
);


/**
 * @param {!proto.viamlabs.service.chat.v1.ChatRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.viamlabs.service.chat.v1.ChatResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.viamlabs.service.chat.v1.ChatResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.viamlabs.service.chat.v1.ChatServiceClient.prototype.chat =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/viamlabs.service.chat.v1.ChatService/Chat',
      request,
      metadata || {},
      methodDescriptor_ChatService_Chat,
      callback);
};


/**
 * @param {!proto.viamlabs.service.chat.v1.ChatRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.viamlabs.service.chat.v1.ChatResponse>}
 *     Promise that resolves to the response
 */
proto.viamlabs.service.chat.v1.ChatServicePromiseClient.prototype.chat =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/viamlabs.service.chat.v1.ChatService/Chat',
      request,
      metadata || {},
      methodDescriptor_ChatService_Chat);
};


module.exports = proto.viamlabs.service.chat.v1;

