"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.struct_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ChatRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    EXTRA_FIELD_NUMBER: builtins.int
    name: builtins.str
    message: builtins.str
    @property
    def extra(self) -> google.protobuf.struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        message: builtins.str = ...,
        extra: google.protobuf.struct_pb2.Struct | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["extra", b"extra"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["extra", b"extra", "message", b"message", "name", b"name"]) -> None: ...

global___ChatRequest = ChatRequest

@typing.final
class ChatResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ANSWER_FIELD_NUMBER: builtins.int
    answer: builtins.str
    def __init__(
        self,
        *,
        answer: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["answer", b"answer"]) -> None: ...

global___ChatResponse = ChatResponse
